/*
 * Copyright (C) 2018 wget
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package be.wget.inpres.java.restaurant.roommanager.guis;

import be.wget.inpres.java.restaurant.config.RestaurantConfig;
import be.wget.inpres.java.restaurant.dataobjects.MainCourse;
import be.wget.inpres.java.restaurant.dataobjects.Plate;
import be.wget.inpres.java.restaurant.fileserializer.DefaultMainCoursesSerializer;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author wget
 */
@SuppressWarnings("serial")
public class AddNewPlateGui extends javax.swing.JDialog implements KeyListener {

    private ArrayList<MainCourse> defaultMainCourses;
    private RestaurantConfig applicationConfig;

    /**
     * Creates new form AboutGui
     */
    public AddNewPlateGui(
            Frame parent,
            RestaurantConfig applicationConfig,
            ArrayList<MainCourse> defaultMainCourses) {
        super(parent, true);
        initComponents();
        this.setTitle("Add new plate");
        this.applicationConfig = applicationConfig;
        this.defaultMainCourses = defaultMainCourses;
        this.newPlateCodeTextField.addKeyListener(this);
        this.newPlateLabelTextField.addKeyListener(this);
        this.newPlatePriceTextField.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        newPlateCodeLabel = new javax.swing.JLabel();
        newPlateCodeTextField = new javax.swing.JTextField();
        newPlateLabelLabel = new javax.swing.JLabel();
        newPlateLabelTextField = new javax.swing.JTextField();
        newPlatePriceLabel = new javax.swing.JLabel();
        newPlatePriceTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("Add new plate");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        newPlateCodeLabel.setText("New plate code:");

        newPlateLabelLabel.setText("New plate label:");

        newPlatePriceLabel.setText("New plate price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newPlateCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPlateCodeTextField)
                    .addComponent(newPlateLabelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPlateLabelTextField)
                    .addComponent(newPlatePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(newPlatePriceTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newPlateCodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPlateCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(newPlateLabelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPlateLabelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(newPlatePriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPlatePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.addNewPlate();
    }//GEN-LAST:event_okButtonActionPerformed

    private void addNewPlate() {
        String newPlateCode = this.newPlateCodeTextField.getText();
        String newPlateLabel = this.newPlateLabelTextField.getText();
        double newPlatePrice;
        try {
            newPlatePrice = Double.parseDouble(this.newPlatePriceTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "The price you specified for the new plate is invalid.",
                "Invalid price",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for (Plate plate: this.defaultMainCourses) {
            if (((MainCourse)plate).getCode().equals(newPlateCode)) {
                JOptionPane.showMessageDialog(this,
                    "The plate code you specified already exists.",
                    "Plate already exists",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        MainCourse newMainCourse = new MainCourse(newPlateLabel, newPlatePrice, newPlateCode);
        this.defaultMainCourses.add(newMainCourse);
        
        ArrayList<Plate> plates = new ArrayList<>();
        for (MainCourse mainCourse: this.defaultMainCourses) {
            plates.add(mainCourse);
        }
        DefaultMainCoursesSerializer mainCoursesSerializer =
            new DefaultMainCoursesSerializer(
                this.applicationConfig,
                plates);
        try {
            mainCoursesSerializer.saveFile();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "An issue occurred when trying to save the file with the main courses.",
                "Serialization impossible",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setVisible(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel newPlateCodeLabel;
    private javax.swing.JTextField newPlateCodeTextField;
    private javax.swing.JLabel newPlateLabelLabel;
    private javax.swing.JTextField newPlateLabelTextField;
    private javax.swing.JLabel newPlatePriceLabel;
    private javax.swing.JTextField newPlatePriceTextField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        if (ke.getKeyCode() == KeyEvent.VK_ENTER) {
            this.addNewPlate();
        }
    }

    @Override
    public void keyReleased(KeyEvent ke) {
    }
}
