/*
 * Copyright (C) 2018 wget
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package be.wget.inpres.java.restaurant.roommanager.guis;

import be.wget.inpres.java.restaurant.config.RestaurantConfig;
import java.awt.Frame;
import java.text.DateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author wget
 */
@SuppressWarnings("serial")
public class PrintingGui extends JDialog {

    RestaurantConfig applicationConfig;
    
    /**
     * Creates new form AboutGui
     */
    public PrintingGui(Frame parent, RestaurantConfig applicationConfig) {
        super(parent, true);
        initComponents();
        this.setTitle("Printing bill...");
        this.setLocationRelativeTo(parent);
        this.applicationConfig = applicationConfig;
        this.animationLabel.setIcon(new ImageIcon(getClass().getResource(
            "/be/wget/inpres/java/restaurant/assets/printing.gif")));
        this.animationLabel.setSize(
            this.animationLabel.getIcon().getIconWidth(),
            this.animationLabel.getIcon().getIconHeight());

        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.SECOND, this.applicationConfig.getPrintJobDelay());
        this.dateTimeLabel.setText(DateFormat.getDateTimeInstance(
            this.applicationConfig.getDateFormat(),
            this.applicationConfig.getDateFormat(),
            this.applicationConfig.getLocale()).format(calendar.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billPrintingLabel = new javax.swing.JLabel();
        etaEndOfPrintingLabel = new javax.swing.JLabel();
        animationLabel = new javax.swing.JLabel();
        dateTimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        billPrintingLabel.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        billPrintingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billPrintingLabel.setText("Printing bill...");

        etaEndOfPrintingLabel.setText("ETA end of printing: ");

        animationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dateTimeLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(animationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(billPrintingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(etaEndOfPrintingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(billPrintingLabel)
                .addGap(18, 18, 18)
                .addComponent(animationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etaEndOfPrintingLabel)
                    .addComponent(dateTimeLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animationLabel;
    private javax.swing.JLabel billPrintingLabel;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JLabel etaEndOfPrintingLabel;
    // End of variables declaration//GEN-END:variables

}
